blank_issues_enabled: false
contact_links:
  - name: Bugs in addon 🐞
    url: https://github.com/FiltersHeroes/PolishCookieConsent/issues/new?template=bug.yml
    about: Please submit bugs inside addon via the Polish Cookie Consent repository. 🙂
