name: Aktualizacja list

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * 0"

jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/sflb_image:3.0.11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_HELPER_ID }}
          private-key: ${{ secrets.PRIVATE_APP_HELPER_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: "PCCassets,PolishCookieConsent"
      - env:
          GIT_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          python3 ./scripts/build.py
