name: Aktualizacja list

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * 0"

jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/vichs_image:2.26.9
    steps:
      - uses: actions/checkout@v2
      - env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          ./scripts/build.sh
