name: Aktualizacja list

on: workflow_dispatch
#   schedule:
#     - cron: "0 10,14,18 * * *"
jobs:
  Aktualizacja:
    runs-on: ubuntu-latest
    container: ghcr.io/filtersheroes/vichs_image:2.26.8
    steps:
      - uses: actions/checkout@v2
      - env:
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          VICHS.sh euCDB.txt plCDB.txt
